// App 域 IPC channels。
export const IPC_APP_CHANNELS = {
  // App 能力
  appSelectWorkspace: "app:selectWorkspace",
  appOpenExternal: "app:openExternal",
  appReadTextFile: "app:readTextFile",
  appWriteTextFile: "app:writeTextFile",
  appReadDirectory: "app:readDirectory",
  appGetFileMetadata: "app:getFileMetadata",
  appLocalSettingsRead: "app:localSettings:read",
  appLocalSettingsPatch: "app:localSettings:patch",
  appCodexProfilesRead: "app:codexProfiles:read",
  appCodexProfilesUpsert: "app:codexProfiles:upsert",
  appCodexProfilesDelete: "app:codexProfiles:delete",
  appCodexProfilesSetActive: "app:codexProfiles:setActive",
  appCodexAuthWriteApiKey: "app:codexAuth:writeApiKey",
  appCodexSkillRootsRead: "app:codexSkillRoots:read",
  appCodexSkillRootsSetForWorkspace: "app:codexSkillRoots:setForWorkspace",
  appListNotificationSounds: "app:notificationSound:list",
  appReadNotificationSoundDataUrl: "app:notificationSound:readDataUrl",
  appSystemNotificationShow: "app:systemNotification:show",
  appFileChangeLogAppend: "app:fileChangeLog:append",
  appReadClipboardImageDataUrl: "app:readClipboardImageDataUrl",
  appReadImageFileDataUrl: "app:readImageFileDataUrl",
  appImageGenerationGenerate: "app:imageGeneration:generate",
  appImageGenerationHistoryList: "app:imageGeneration:historyList",
  appImageGenerationHistoryDelete: "app:imageGeneration:historyDelete",
  appImportBackgroundImage: "app:background:import",
  appClearBackgroundImage: "app:background:clear",
  appRemoteSyncGetState: "app:remoteSync:getState",
  appRemoteSyncLogin: "app:remoteSync:login",
  appRemoteSyncLogout: "app:remoteSync:logout",
  appRemoteSyncFlush: "app:remoteSync:flush",
  // 窗口控制（自定义标题栏）
  appWindowGetState: "app:window:getState",
  appWindowMinimize: "app:window:minimize",
  appWindowToggleMaximize: "app:window:toggleMaximize",
  appWindowClose: "app:window:close",
  appWindowState: "app:window:state",
  appWindowClosingState: "app:window:closingState",
  appRemoteSyncState: "app:remoteSync:state",
} as const;
