// App 域 IPC channels。
export const IPC_APP_CHANNELS = {
  // App 能力
  appSelectWorkspace: "app:selectWorkspace",
  appOpenExternal: "app:openExternal",
  appReadTextFile: "app:readTextFile",
  appWriteTextFile: "app:writeTextFile",
  appReadDirectory: "app:readDirectory",
  appGetFileMetadata: "app:getFileMetadata",
  appLocalSettingsRead: "app:localSettings:read",
  appLocalSettingsPatch: "app:localSettings:patch",
  appListNotificationSounds: "app:notificationSound:list",
  appReadNotificationSoundDataUrl: "app:notificationSound:readDataUrl",
  appSystemNotificationShow: "app:systemNotification:show",
  appFileChangeLogAppend: "app:fileChangeLog:append",
  appReadClipboardImageDataUrl: "app:readClipboardImageDataUrl",
  appReadImageFileDataUrl: "app:readImageFileDataUrl",
  appImportBackgroundImage: "app:background:import",
  appClearBackgroundImage: "app:background:clear",
  appInvokeWindowsVoiceTyping: "app:invokeWindowsVoiceTyping",
  appUpdateGetState: "app:update:getState",
  appUpdateCheck: "app:update:check",
  appUpdateDownload: "app:update:download",
  appUpdateRestartToInstall: "app:update:restartToInstall",
  appRemoteSyncGetState: "app:remoteSync:getState",
  appRemoteSyncLogin: "app:remoteSync:login",
  appRemoteSyncLogout: "app:remoteSync:logout",
  appRemoteSyncFlush: "app:remoteSync:flush",
  // 窗口控制（自定义标题栏）
  appWindowGetState: "app:window:getState",
  appWindowMinimize: "app:window:minimize",
  appWindowToggleMaximize: "app:window:toggleMaximize",
  appWindowClose: "app:window:close",
  appWindowState: "app:window:state",
  appWindowClosingState: "app:window:closingState",
  appUpdateState: "app:update:state",
  appRemoteSyncState: "app:remoteSync:state",
} as const;
